services:
  postgres:
    image: postgres:latest
    container_name: ${COMPOSE_PROJECT_NAME}-postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - ./apps/solutionazer-backend/docker/postgres/${COMPOSE_PROJECT_NAME}:/var/lib/postgresql/data
